create table if not exists tenants (
  id bigint generated always as identity primary key,
  property_id bigint references properties(id) on delete set null,
  name text not null,
  dni text default '',
  cuil text default '',
  phone text default '',
  email text default '',
  company text default '',
  employment_status text default '',
  occupants int,
  pets text default '',
  family text default '',
  "references" text default '',
  insurance text default '',
  owner_name text default '',
  owner_phone text default '',
  owner_email text default '',
  start_date date not null,
  end_date date not null,
  currency text not null default 'ARS',
  payday int,
  deposit numeric default 0,
  late_coefficient numeric default 0,
  update_freq text default 'trimestral', 
  update_index text default 'ICL',
  guarantee text default '',
  status_override text default '', 
  guarantors jsonb not null default '[]',      
  rent_history jsonb not null default '[]',    
  payments jsonb not null default '[]',        
  notes text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table tenants enable row level security;
